namespace: 
  name: prerequisite 
secret: 
  name: prerequisite
deployment: 
  name: prerequisite
  replicas: 2
  ports: 
    containerPort: 8085
  image: 
    repo: musatee11/springboot
    tag: latest

service: 
  name: prerequisite
  type: NodePort
  ports:
    targetPort: 8085
    port: 80