namespace: 
  name: dev 

deployment: 
  replicas: 2
  ports: 
    containerPort: 8085
  image: 
    repo: musatee11/springboot
    tag: latest

service: 
  type: NodePort
  ports:
    targetPort: 8085
    port: 80 